name: Build and publish container image

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hadolint Dockerfile Linter
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: Dockerfile
          format: sarif
          output-file: hadolint-results.sarif

      - name: Update Pull Request with Hadolint Report
        uses: actions/github-script@v6
        if: ${{ failure() }}
        with:
          script: |
            const output = `
            #### Hadolint: \`${{ steps.hadolint.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Kaniko build
        uses: aevea/action-kaniko@83ddee1c8b2f6e5b22b0985c5b3a8288f76c25b0
        with:
          image: bats-dns-resolution-testing
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.pull_request.head.sha }}

  testing:  
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stv-io/bats-dns-resolution-testing/bats-dns-resolution-testing:${{ github.event.pull_request.head.sha }} 
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: run tests
        run: echo "testing"
